name: vegan_liverpool
version: 0.0.1+6
publish_to: none
description: Food, Grocery delivery platform for Vegan products and food, with a built in wallet running on the Fuse network
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  analyzer: ">=3.0.0 <3.3.0"
  animations: ^2.0.2
  another_flushbar: ^1.10.24
  app_tracking_transparency: ^2.0.1
  auto_route: ^3.2.1
  auto_size_text: ^3.0.0-nullsafety.0
  auto_size_text_field: ^1.0.0-nullsafety.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  carrier_info: ^2.0.4
  confetti: ^0.6.0
  contacts_service: ^0.6.1
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  decimal: ^2.1.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^11.2.6
  firebase_remote_config: ^2.0.2
  fl_chart: ^0.50.0
  flare_flutter: ^3.0.1
  flex_color_scheme: ^4.2.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_dotenv: ^5.0.0
  flutter_form_builder: ^7.1.0
  form_builder_extra_fields: ^7.1.0
  form_builder_validators: ^7.4.0
  flutter_inappwebview: ^5.3.2
  flutter_localized_locales: ^2.0.2
  flutter_platform_widgets: ^1.9.5
  flutter_redux: ^0.9.0
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_sticky_header: ^0.6.0
  flutter_stripe: ^2.4.0
  flutter_svg: ^1.0.3
  flutter_udid: ^2.0.0
  flutter_web_browser: ^0.17.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  geocoding: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.1
  google_api_headers: ^1.2.0
  grouped_list: ^4.0.0
  image_picker: ^0.8.2
  injectable: ^1.5.3
  json_annotation: ^4.0.1
  local_auth: ^1.1.6
  logger: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  number_display: ^3.0.0
  package_info: ^2.0.2
  permission_handler: ^9.2.0
  phone_number: ^0.12.0+1
  pin_code_fields: ^7.2.0
  platform: ^3.1.0
  qr_flutter: ^4.0.0
  rate_my_app: ^1.1.0+1
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^0.1.4
  scan: ^1.4.3
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  sentry_flutter: ^6.4.0
  share_plus: ^4.0.3
  shimmer: ^2.0.0
  simple_animations: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.9
  uuid: ^3.0.6
  webview_flutter: ^3.0.1
  wallet_core:
    git:
      url: https://github.com/fuseio/wallet_core.git
      ref: master
  ethereum_addresses:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  flutter_segment:
    git:
      url: https://github.com/fuseio/flutter-segment.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.8
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.1
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.3
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Fat Cheeks
      fonts:
        - asset: assets/fonts/FatCheeks-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
          weight: 500
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
